modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "patternmasters-fix"
version = "${version}"
displayName = "Patternmaster's Fix"
authors = "beholderface"
description = '''
A simple mod that makes Patternmaster's Purification stop erroring when used on non-static patterns.
'''
#logoFile = ""

[[dependencies.patternmasters-fix]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.patternmasters-fix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.patternmasters-fix]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
